### ISSUE TITLE
aws install issue

### ISSUE THREAD

**Issue by JamesMaxwellHarrison** [sergiocorreia/quipucamayoc#4]
Hello,

I am having trouble using the command ```quipu aws install```. I have installed quipucamayoc and downloaded the aws cli and configured my credentials. I have redacted my account id below, but I have verified that it matches my account. Any help would be appreciated.

Thanks!

Setting up AWS for quipucamayoc:
11:17:26.1 | INFO     | Parameters:
11:17:26.1 | INFO     |   - region = us-east-1
11:17:26.1 | INFO     |   - account_id = [redacted]
11:17:26.1 | INFO     |   - topic_arn = arn:aws:sns:us-east-1:[redacted]:AmazonTextractQuipu
11:17:26.1 | INFO     |   - role_arn = arn:aws:iam::[redacted]:role/quipu-textract
11:17:26.1 | INFO     |   - queue_url = https://queue.amazonaws.com/[redacted]/quipu-queue
11:17:26.1 | INFO     |   - queue_arn = None
11:17:26.1 | INFO     |   - subscription_arn = None
11:17:26.1 | INFO     |   - bucket = quipu-[redacted]
11:17:26.1 | INFO     | Current AWS user: [redacted]
11:17:26.1 | INFO     | Creating clients...
11:17:26.9 | INFO     | Creating bucket "quipu-[redacted]"
11:17:27.7 | INFO     |   - Bucket "quipu-[redacted]" exists; deleting it
11:17:29.9 | INFO     |   - Making bucket private
11:17:30.1 | INFO     | Creating SNS topic "AmazonTextractQuipu"...
11:17:30.8 | INFO     |   - Deleted SNS topic
11:17:31.2 | INFO     |   - SNS topic ARN = "arn:aws:sns:us-east-1:[redacted]:AmazonTextractQuipu"
11:17:31.2 | INFO     | Creating SQS standard queue "quipu-queue"...
11:17:31.2 | INFO     |   - Retrieving list of existing queues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\Anaconda\envs\py311\Scripts\quipu.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda\envs\py311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\py311\Lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\py311\Lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\py311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\py311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Anaconda\envs\py311\Lib\site-packages\quipucamayoc\cli.py", line 42, in aws
    install_aws()
  File "D:\Anaconda\envs\py311\Lib\site-packages\quipucamayoc\aws_setup.py", line 408, in install_aws
    create_sqs_queue(quipu, sqs_client, logger)
  File "D:\Anaconda\envs\py311\Lib\site-packages\quipucamayoc\aws_setup.py", line 270, in create_sqs_queue
    assert quipu.queue_url == r['QueueUrl']
AssertionError

**Comment by psungho** [comment]
seems this issue still happens
