### ISSUE TITLE
quipu aws install fails

### ISSUE THREAD

**Issue by puppy8472** [sergiocorreia/quipucamayoc#8]
Hi, 

After setting up aws via aws configure, setting region to us-east-1 (I have also tried us-east-2) and default output to JSON, I get the following error and am unable to proceed. Please see the output below. Thank you!

1:09:07.8 | INFO     |   - Bucket "quipu-179710001707" exists; deleting it
11:09:10.5 | INFO     |   - Making bucket private
11:09:10.8 | INFO     | Creating SNS topic "AmazonTextractQuipu"...
11:09:11.8 | INFO     |   - Deleted SNS topic
11:09:12.5 | INFO     |   - Deleted 1 SNS topic subscriptions
11:09:14.0 | INFO     |   - SNS topic ARN = "arn:aws:sns:us-east-1:179710001707:AmazonTextractQuipu"
11:09:14.0 | INFO     | Creating SQS standard queue "quipu-queue"...
11:09:14.0 | INFO     |   - Retrieving list of existing queues
Traceback (most recent call last):
  File "/Users/puppy/anaconda3/bin/quipu", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/Users/puppy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/puppy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/puppy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/puppy/anaconda3/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/puppy/anaconda3/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/puppy/anaconda3/lib/python3.11/site-packages/quipucamayoc/cli.py", line 42, in aws
    install_aws()
  File "/Users/puppy/anaconda3/lib/python3.11/site-packages/quipucamayoc/aws_setup.py", line 408, in install_aws
    create_sqs_queue(quipu, sqs_client, logger)
  File "/Users/puppy/anaconda3/lib/python3.11/site-packages/quipucamayoc/aws_setup.py", line 270, in create_sqs_queue
    assert quipu.queue_url == r['QueueUrl']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

**Comment by sergiocorreia** [comment]
Could you edit the aws_setup.py line installed in your system (probably in the `Lib\site-packages` subfolder of your Python install) and replace this line

```
assert quipu.queue_url == r['QueueUrl']
```

With

```
print(quipu.queue_url)
print(r['QueueUrl'])
```

This assertion is pretty harmless, and can be commented out, but I'm still unsure about for many users it does not hold.

**Comment by puppy8472** [comment]
Thank you. This resolved the issue!

**Comment by sergiocorreia** [comment]
Great! Also, do let me know if possible what did the print() statements return, so I can fix it in the repo.

**Comment by puppy8472** [comment]
They ran the following:

https://queue.amazonaws.com/179710001707/quipu-queue
https://sqs.us-east-1.amazonaws.com/179710001707/quipu-queue
